"use client";
import { useLayoutEffect } from "react";

type Ember={el:HTMLSpanElement;animation:Animation;ring:boolean};
const rand=(a:number,b:number)=>Math.random()*(b-a)+a;
function sizeProfile(ring:boolean){const r=Math.random();if(r<.035)return rand(1.4,2.1);if(r<.20)return rand(2.3,3.4);if(r<.46)return rand(3.4,4.8);if(r<.70)return rand(4.8,6.2);if(r<.94)return rand(6.2,7.8);if(r<.985)return rand(8,10.5);return ring?rand(10.5,13):rand(9,11)}
export default function HeroParticleEngine(){useLayoutEffect(()=>{const scene=document.querySelector<HTMLElement>(".hero-depth-scene");const ring=document.querySelector<HTMLElement>(".hero-orbit-one");const layer=document.createElement("div");layer.className="hero-live-embers";Object.assign(layer.style,{position:"fixed",inset:"0",overflow:"visible",pointerEvents:"none",zIndex:"2",isolation:"isolate"});document.body.appendChild(layer);const embers:Ember[]=[];let stopped=false,spawnTimer=rand(55,120),raf=0;
const make=(x:number,y:number,angle:number,isRing=false,initial=false)=>{if(embers.length>=430)return;const size=sizeProfile(isRing),el=document.createElement("span");el.className="hero-live-ember";Object.assign(el.style,{position:"absolute",left:`${x}px`,top:`${y}px`,width:`${size}px`,height:`${size}px`,borderRadius:"50%",opacity:"0",background:"radial-gradient(circle,rgba(255,224,145,.98) 0%,rgba(255,145,34,.76) 45%,rgba(255,75,8,0) 100%)",boxShadow:`0 0 ${Math.max(4,size*2.6)}px rgba(255,126,22,.30)`,willChange:"transform,opacity",contain:"layout style paint"});const distance=isRing?rand(48,155):rand(35,135),dx=Math.cos(angle)*distance,dy=Math.sin(angle)*distance+(isRing?rand(8,32):rand(12,48)),driftX=rand(-38,38),driftY=rand(-8,30),duration=initial?rand(18000,28000):rand(14500,23000),alpha=rand(.34,.80),scaleEnd=rand(.30,.55);const animation=el.animate([{transform:"translate3d(0,0,0) scale(.72)",opacity:0},{transform:`translate3d(${dx*.18}px,${dy*.18}px,0) scale(1)`,opacity:alpha,offset:.12},{transform:`translate3d(${dx*.52+driftX*.25}px,${dy*.52+driftY*.22}px,0) scale(.80)`,opacity:alpha*.74,offset:.55},{transform:`translate3d(${dx+driftX}px,${dy+driftY}px,0) scale(${scaleEnd})`,opacity:0,offset:.93},{transform:`translate3d(${dx+driftX*1.15}px,${dy+driftY+rand(8,22)}px,0) scale(.16)`,opacity:0}],{duration,easing:"linear",fill:"both"});layer.appendChild(el);embers.push({el,animation,ring:isRing});animation.onfinish=()=>{el.remove();const i=embers.findIndex(p=>p.el===el);if(i>=0)embers.splice(i,1)}};
const seedAmbient=()=>{const w=innerWidth,h=innerHeight;for(let i=0;i<185;i++){const x=rand(w*.08,w*.92),y=rand(h*.08,h*.78);if(y>h*.60&&Math.random()<.64)continue;make(x,y,rand(-Math.PI*.16,Math.PI*.16),false,true)}};
const ringPoint=()=>{if(!ring)return;const rr=ring.getBoundingClientRect(),a=rand(0,Math.PI*2),radius=Math.min(rr.width,rr.height)*rand(.50,.525);make(rr.left+rr.width/2+Math.cos(a)*radius,rr.top+rr.height/2+Math.sin(a)*radius,a+rand(-.28,.28),true)};
const updateHeat=()=>{if(!ring)return;const rr=ring.getBoundingClientRect();};
seedAmbient();for(let i=78;i>0;i--)ringPoint();const tick=()=>{if(stopped)return;updateHeat();const activeRing=embers.reduce((n,e)=>n+(e.ring?1:0),0);if(ring&&activeRing<78){const count=activeRing<62?(Math.random()<.65?2:3):1;for(let i=0;i<count;i++)ringPoint()}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>{stopped=true;cancelAnimationFrame(raf);for(const e of embers)e.animation.cancel();layer.remove()}},[]);return null}
